ejemplo1:
	kotlinc input1.kt -nowarn -include-runtime -d input1.jar && java -jar input1.jar && rm input1.jar

ejemplo2:
	kotlinc input2.kt -nowarn -include-runtime -d input2.jar && java -jar input2.jar && rm input2.jar

ejemplo3:
	kotlinc input3.kt -nowarn -include-runtime -d input3.jar && java -jar input3.jar && rm input3.jar

ejemplo4:
	kotlinc input4.kt -nowarn -include-runtime -d input4.jar && java -jar input4.jar && rm input4.jar